name: adv_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.17.1
  - anyio=4.11.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - colorlog=6.10.1
  - comm=0.2.3
  - contourpy=1.3.2
  - cpython=3.10.19
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - ffmpeg=8.0.0
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2025.10.0
  - gdk-pixbuf=2.44.4
  - giflib=5.2.2
  - glslang=16.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - greenlet=3.2.4
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - kaldi=5.5.1172
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcxx=21.1.5
  - libde265=1.0.15
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenvino=2025.2.0
  - libopenvino-arm-cpu-plugin=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libtiff=4.7.1
  - libtorch=2.8.0
  - libusb=1.0.29
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - mako=1.3.10
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numpy=2.2.6
  - openfst=1.8.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.17.0
  - optuna=4.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=12.0
  - pyobjc-framework-cocoa=12.0
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.8.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rav1e=0.7.1
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.28.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - sdl2=2.32.56
  - sdl3=3.2.26
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shaderc=2025.4
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - spirv-tools=2025.4
  - sqlalchemy=2.0.44
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.3.0
  - torchaudio=2.8.0
  - torchcodec=0.8.1
  - torchvision=0.24.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - causal-learn==0.1.4.3
      - clarabel==0.11.1
      - click==8.1.8
      - cloudpickle==3.1.2
      - codecarbon==3.0.8
      - cryptography==44.0.3
      - cvxpy==1.7.3
      - cython==3.2.1
      - datasets==4.4.1
      - dill==0.4.0
      - dowhy==0.14
      - fief-client==0.20.0
      - flwr==1.23.0
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphviz==0.21
      - grpcio==1.76.0
      - grpcio-health-checking==1.62.3
      - hf-xet==1.2.0
      - httpx==0.27.2
      - huggingface-hub==0.36.0
      - imageio==2.37.2
      - iterators==0.0.2
      - jwcrypto==1.5.6
      - lazy-loader==0.4
      - lime==0.2.0.1
      - llvmlite==0.45.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - momentchi2==0.1.8
      - multidict==6.7.0
      - multiprocess==0.70.18
      - numba==0.62.1
      - nvidia-ml-py==13.580.82
      - osqp==1.0.5
      - pathspec==0.12.1
      - propcache==0.4.1
      - protobuf==4.25.8
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pycryptodome==3.23.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydot==4.0.1
      - pytorch-ranger==0.1.1
      - questionary==2.1.1
      - rapidfuzz==3.14.3
      - regex==2025.11.3
      - rich==13.9.4
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scs==3.2.9
      - sentry-sdk==2.44.0
      - shap==0.49.1
      - shellingham==1.5.4
      - slicer==0.0.8
      - smmap==5.0.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - tifffile==2025.5.10
      - tokenizers==0.22.1
      - tomli-w==1.2.0
      - torch-optimizer==0.3.0
      - transformers==4.57.1
      - typer==0.12.5
      - typing-inspection==0.4.2
      - wandb==0.23.0
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - yarl==1.22.0
      - yaspin==3.3.0
prefix: /opt/anaconda3/envs/adv_ai
